; Enter your authentication details here for the script to send authorized requests to Twitch API. https://twitchtokengenerator.com/
; Select "Bot Chat Token" and authenticate with your Twitch account. Copy the ACCESS TOKEN, which is your OAUTH_TOKEN.
; e.g. CHANNEL_NAME = mkay_sg
; e.g. OAUTH_TOKEN = oauth:exampletokengibberishvalue
; IMPORTANT - DO NOT SHARE YOUR OAUTH TOKEN FOR SECURITY REASONS OR SHARE THIS SCRIPT WHEN YOUR TOKEN'S IN IT. No quotes required.

[AUTHENTICATION]
CHANNEL_NAME = example_channel_name
OAUTH_TOKEN = oauth:exampletokengibberishvalue

; Select which syntax you'd like chat to use. Possible Values:
; XBX
; PS
; NINT
; You can view the wiki for the syntax at xxx or via !twitchpad command after the bot has successfully started 

[INPUT_SCHEME]
SCHEME = XBX

; Determine voting mode's duration for chat to cast their votes - accepts only within a range from 15 to 120 seconds.
; e.g. SECONDS = 15

[VOTING_DURATION]
SECONDS = 30